(dp1
S'output'
p2
S"<type 'exceptions.KeyError'> 11"
p3
sS'layer'
p4
S'/var/www/python/web2py/applications/ElementarTrumpf/controllers/ElementarTrumpfControl.py'
p5
sS'code'
p6
S'<code object <module> at 0x6f312a40, file "/var/www/python/web2py/applications/ElementarTrumpf/controllers/ElementarTrumpfControl.py", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/var/www/python/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/var/www/python/web2py/applications/ElementarTrumpf/controllers/ElementarTrumpfControl.py", line 37, in <module>\n  File "/var/www/python/web2py/gluon/globals.py", line 421, in <lambda>\n    self._caller = lambda f: f()\n  File "/var/www/python/web2py/applications/ElementarTrumpf/controllers/ElementarTrumpfControl.py", line 24, in kartenZiehen\n    aiMonster= monsters[random.randint(0, len(monsterName))]\nKeyError: 11\n'
p11
s.